### PR TITLE
Fix pluralization issue (in order to properly pluralize/singularize woman/women!)

### PR DESCRIPTION
**Pull request by glaukommatos**
Because I care. :heart:

### CODE REVIEW

**Comment by fsmanuel** [comment]
@glaukommatos thanks for caring.
> Ember Inflector aims to be compatible with [ActiveSupport::Inflector](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb) from Ruby on Rails

Rails has decided to freeze its default inflection rules, and to match parity so have we.

One can still add additional app specific inflections, see: https://github.com/stefanpenner/ember-inflector#usage for further examples of how one does this.

**Comment by glaukommatos** [comment]
Understandable. Thank you.

**Comment by stefanpenner** [comment]
@glaukommatos if it is an omission, then yes we would like it.

**Comment by stefanpenner** [comment]
this does not appear to be in the irregular pairs https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb#L61-L66

**Comment by fsmanuel** [comment]
@stefanpenner good catch.

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L378

**Comment by stefanpenner** [comment]
Ouch this is a bug. I'm swamped, anyone else want to take a shot?

**Comment by ofbriggs** [comment]
I can look into this on the weekend if no one else can address it sooner.

**Comment by glaukommatos** [comment]
I'd be glad to help as well, although I'm not as familiar with the code base.

**Comment by glaukommatos** [comment]
Would it be overkill to pull in the SingularToPlural / PluralToSingular test cases from the ActiveSupport::Inflector [test cases](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activesupport/test/inflector_test_cases.rb)?

**Comment by glaukommatos** [comment]
I hope someone can take a look at the changes I made. I believe they fix the issue. I apologize if it's not the most stylish and idiomatic JavaScript- hopefully it's a good start.

**Comment by glaukommatos** [comment]
Current PR breaks some capitalization stuff, I'm adding some more tests.

**Comment by fsmanuel** [comment]
@glaukommatos LGTM. I like to have all the tests from ActiveSupport so we are closer to match parity. I'll review when I'm home.

**Comment by glaukommatos** [comment]
@fsmanuel I just fixed some issues with capitalization that I introduced accidentally, and I added a few more tests. I rebased to clean up the commit history.

**Comment by glaukommatos** [comment]
@ofbriggs removed the duplicate assertion :heavy_check_mark:

**Comment by fsmanuel** [comment]
@ofbriggs you can merge if there are no more objection. @glaukommatos thanks

**Comment by ofbriggs** [comment]
Merged, thanks @glaukommatos!

**Comment by stefanpenner** [comment]
@ofbriggs I can't remember. Do you have npm publish? If so feel to release a minor

**Comment by ofbriggs** [comment]
@stefanpenner I don't think so.

**Comment by glaukommatos** [comment]
Yay. Thanks. :+1:

**Pull request merged**
